title: JingwenWang's Homepage
page-top-title: JingwenWang
top-section-bg-text: Electronic Information
home-subtitle: JingwenWang&ensp;|&ensp;王婧雯
copyright-text: '&copy; JingwenWang 2025-2028. All Rights Reserved.'
